version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  plugins = ["vue"]
  dialect = "typescript"
  style_guide = "standard"
  dependency_file_paths = ["desktopapp/package.json"]
